var app = angular.module("myapp",[]);
app.directive("header",function(){
	return {
        
		template :`<div class="container"> <nav style="height: 50px,background-color: #33383b" class="navbar navbar-inverse navbar-fixed-top" role="navigation"> <div class="container-fluid"> <div class="navbar-header"> <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <a class="navbar-brand" href="#">Brand</a> </div><div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> <ul style="font-size: 15px" class="nav navbar-nav navbar-center"> <li><span style="padding-left:400px "></span></li><li ><a href="/index.html">Home</a></li><li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a> <ul class="dropdown-menu"> <li><a href="/cigrette.html">Cigarettes</a></li><li><a href="#">Another action</a></li><li><a href="#">Something else here</a></li><li class="divider"></li><li><a href="#">Separated link</a></li><li class="divider"></li><li><a href="#">One more separated link</a></li></ul> </li><li><a href="#">Contact us</a></li></ul> <ul class="nav navbar-nav navbar-right"> <li><a href="#">Link</a></li><li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a> <ul class="dropdown-menu"> <li><a href="#">Action</a></li><li><a href="#">Another action</a></li><li><a href="#">Something else here</a></li><li class="divider"></li><li><a href="#"><span style="font-size: 18px" >Separated link</span></a></li></ul> </li></ul> </div></div></nav> </div>`,
		restrict :"E"
	}
});
app.directive("foooter",function(){
	return {
		template :` <footer class="footer-distributed"> <div class="footer-left"> <h3>Company<span>logo</span></h3> <p class="footer-links"> <a href="#">Home</a> · <a href="#">Blog</a> · <a href="#">Pricing</a> · <a href="#">About</a> · <a href="#">Faq</a> · <a href="#">Contact</a> </p><p class="footer-company-name">Company Name &copy; 2015</p></div><div class="footer-center"> <div> <i class="fa fa-map-marker"></i> <p><span>21 Revolution Street</span> Paris, France</p></div><div> <i class="fa fa-phone"></i> <p>+1 555 123456</p></div><div> <i class="fa fa-envelope"></i> <p><a href="mailto:support@company.com">support@company.com</a></p></div></div><div class="footer-right"> <p class="footer-company-about"> <span>About the company</span> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p><div class="footer-icons"> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-linkedin"></i></a> <a href="#"><i class="fa fa-github"></i></a> </div></div></footer>`,
		restrict :"E"
	}
});